[package]
name = "bashman_core"
version = "0.4.2"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2021"
rust-version = "1.70"
description = "The backing library for Cargo Bashman."
repository = "https://github.com/Blobfolio/bashman"
publish = false

[dependencies]
adbyss_psl = "0.8.*"
argyle = "0.6.*"
cargo_metadata = "=0.18.0"
fyi_msg = "0.11.*"
indexmap = "=2.0.0"
libdeflater = "=1.19.0"
oxford_join = "0.2.*"
trimothy = "0.1.*"
utc2k = "0.6.*"

[dependencies.serde]
version = "1.0.*"
features = [ "derive" ]

[dependencies.toml]
version = "0.8.*"
features = [ "preserve_order" ]
