[package]
name = "bashman_core"
version = "0.2.4"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "The backing library for Cargo Bashman."
repository = "https://github.com/Blobfolio/bashman"
publish = false

[dependencies]
argyle = "0.4.*"
fyi_msg = "0.8.*"
indexmap = "1.6.*"
libdeflater = "0.7.*"

[dependencies.chrono]
version = "0.4.*"
default-features = false
features = [ "clock", "std" ]

[dependencies.serde]
version = "1.0.*"
features = [ "derive" ]

[dependencies.toml]
version = "0.5.*"
features = [ "preserve_order" ]
