[package]
name = "bashman_core"
version = "0.3.3"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2021"
rust-version = "1.56"
description = "The backing library for Cargo Bashman."
repository = "https://github.com/Blobfolio/bashman"
publish = false

[dependencies]
argyle = "0.5.*"
cargo_metadata = "0.14.*"
fyi_msg = "0.9.*"
indexmap = "1.8.*"
libdeflater = "0.7.*"
once_cell = "1.9.*"
oxford_join = "0.2.*"
regex = "1.5.*"
utc2k = "0.3.*"

[dependencies.serde]
version = "1.0.*"
features = [ "derive" ]

[dependencies.toml]
version = "0.5.*"
features = [ "preserve_order" ]
