.TH "CARGO BASHMAN" "1" "VARIABLEDATE" "bashman v0.5.2" "User Commands"
.SH NAME
CARGO BASHMAN \- Manual page for bashman v0.5.2.
.SH DESCRIPTION
The backing library for Cargo Bashman.
.SS USAGE:
.TP
bashman [SUBCOMMAND] [FLAGS] [OPTIONS] <MSG>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.SS OPTIONS:
.TP
\fB\-f\fR, \fB\-\-features\fR <FEATURE(S)>
Comma\-separated list of optional features to include when generating CREDITS.md.
.SS TRAILING:
.TP
\fB<MSG>\fR
The message!
.SS SUBCOMMANDS:
.TP
\fBaction\fR
Take action! Now!
.TP
\fBmake\fR
Make stuff.
.SH EARLY EXIT
Press CTRL+C once to quit as soon as the already\-in\-progress operations have
.RE
finished (ignoring any pending items still in the queue).
.SS OPTIMIZERS:
.TP
\fBMozJPEG\fR
<https://github.com/mozilla/mozjpeg>
.TP
\fBOxipng\fR
<https://github.com/shssoichiro/oxipng>
.TP
\fBZopflipng\fR
<https://github.com/google/zopfli>
