[package]
name = "bashman"
version = "0.5.2"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2021"
description = "The backing library for Cargo Bashman."
repository = "https://github.com/Blobfolio/bashman"
publish = false

[package.metadata.bashman]
name = "Cargo BashMan"
bash-dir = "./"
man-dir = "./"
credits-dir = "./"

[[package.metadata.bashman.subcommands]]
cmd = "make"
description="Make stuff."

[[package.metadata.bashman.subcommands]]
cmd = "action"
description="Take action! Now!"

[[package.metadata.bashman.switches]]
short = "-h"
long = "--help"
description = "Print help information."
subcommands = ["", "action", "make"]

[[package.metadata.bashman.switches]]
long = "--no-bash"
description = "Do not generate BASH completions."
subcommands = ["make"]

[[package.metadata.bashman.switches]]
long = "--no-credits"
description = "Do not generate CREDITS.md."
subcommands = ["make"]

[[package.metadata.bashman.switches]]
long = "--no-man"
description = "Do not generate MAN page(s)."
subcommands = ["make"]

[[package.metadata.bashman.switches]]
short = "-V"
long = "--version"
description = "Print application version."
subcommands = ["action"]

[[package.metadata.bashman.options]]
short = "-f"
long = "--features"
description = "Comma-separated list of optional features to include when generating CREDITS.md."
label = "<FEATURE(S)>"
path = false

[[package.metadata.bashman.options]]
short = "-m"
long = "--manifest-path"
description = "Path to the Cargo.toml file to use."
label = "<Cargo.toml>"
path = true
subcommands = ["action", "make"]

[[package.metadata.bashman.arguments]]
label = "<MSG>"
description = "The message!"

[[package.metadata.bashman.sections]]
name = "EARLY EXIT"
inside = false
lines = [
	"Press CTRL+C once to quit as soon as the already-in-progress operations have",
	"finished (ignoring any pending items still in the queue).",
]

[[package.metadata.bashman.sections]]
name = "OPTIMIZERS"
inside = true
items = [
	[ "MozJPEG", "<https://github.com/mozilla/mozjpeg>" ],
	[ "Oxipng", "<https://github.com/shssoichiro/oxipng>" ],
	[ "Zopflipng", "<https://github.com/google/zopfli>" ]
]

[dependencies]
cargo_metadata = "=0.18.1"

[dependencies.toml]
version = "0.8.*"
features = [ "preserve_order" ]
optional = true

[features]
default = []
foo = [ "toml" ]
bar = []
