.TH "CARGO BASHMAN MAKE" "1" "VARIABLEDATE" "bashman make v0.5.2" "User Commands"
.SH NAME
MAKE \- Manual page for bashman make v0.5.2.
.SH DESCRIPTION
Make stuff.
.SS USAGE:
.TP
bashman make [FLAGS] [OPTIONS]
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-\-no\-bash\fR
Do not generate BASH completions.
.TP
\fB\-\-no\-credits\fR
Do not generate CREDITS.md.
.TP
\fB\-\-no\-man\fR
Do not generate MAN page(s).
.SS OPTIONS:
.TP
\fB\-m\fR, \fB\-\-manifest\-path\fR <Cargo.toml>
Path to the Cargo.toml file to use.
.SH EARLY EXIT
Press CTRL+C once to quit as soon as the already\-in\-progress operations have
.RE
finished (ignoring any pending items still in the queue).
.SS OPTIMIZERS:
.TP
\fBMozJPEG\fR
<https://github.com/mozilla/mozjpeg>
.TP
\fBOxipng\fR
<https://github.com/shssoichiro/oxipng>
.TP
\fBZopflipng\fR
<https://github.com/google/zopfli>
