.TH "CARGO BASHMAN" "1" "November 2022" "Cargo BashMan v0.3.14" "User Commands"
.SH NAME
Cargo BashMan \- Manual page for cargo\-bashman v0.3.14.
.SH DESCRIPTION
A Cargo plugin to generate BASH completions and MAN pages.
.SS USAGE:
.TP
cargo\-bashman [FLAGS] [OPTIONS]
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-\-no\-bash\fR
Do not generate BASH completions.
.TP
\fB\-\-no\-credits\fR
Do not generate CREDITS.md.
.TP
\fB\-\-no\-man\fR
Do not generate MAN page(s).
.TP
\fB\-V\fR, \fB\-\-version\fR
Print application version.
.SS OPTIONS:
.TP
\fB\-f\fR, \fB\-\-features\fR <Cargo.toml>
Comma\-separated list of optional features to include when generating CREDITS.md.
.TP
\fB\-m\fR, \fB\-\-manifest\-path\fR <Cargo.toml>
Path to the Cargo.toml file to use.
