.TH "CARGO BASHMAN" "1" "October 2021" "Cargo BashMan v0.2.8" "User Commands"
.SH NAME
Cargo BashMan \- Manual page for cargo\-bashman v0.2.8.
.SH DESCRIPTION
BashMan is a Cargo plugin that helps you generate BASH completions and/or MAN pages for your Rust project.
.SS USAGE:
.TP
cargo\-bashman [FLAGS] [OPTIONS]
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print application version.
.SS OPTIONS:
.TP
\fB\-m\fR, \fB\-\-manifest\-path\fR <Cargo.toml>
Path to the Cargo.toml file to use.
